// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REP_CRIME01.Police.Infrastructure.Context;

namespace REP_CRIME01.Police.Infrastructure.Migrations
{
    [DbContext(typeof(PoliceContext))]
    [Migration("20210707175432_AddUniqueConstraintOnLawEnforcementCode")]
    partial class AddUniqueConstraintOnLawEnforcementCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("REP_CRIME01.Police.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CrimeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CrimeReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LawEnforcementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LawEnforcementId");

                    b.ToTable("Case");
                });

            modelBuilder.Entity("REP_CRIME01.Police.Domain.Entities.LawEnforcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoliceDepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("LawEnforcement");
                });

            modelBuilder.Entity("REP_CRIME01.Police.Domain.Entities.Case", b =>
                {
                    b.HasOne("REP_CRIME01.Police.Domain.Entities.LawEnforcement", "LawEnforcement")
                        .WithMany("Cases")
                        .HasForeignKey("LawEnforcementId");

                    b.Navigation("LawEnforcement");
                });

            modelBuilder.Entity("REP_CRIME01.Police.Domain.Entities.LawEnforcement", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
