version: '3.4'

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  
  sqldata:
    container_name: sqldata
    environment:     
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd2021
    restart: always
    ports:
      - "1403:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
     - "5672:5672"
     - "15672:15672"

  rep_crime01.crime.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings:ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings:DatabaseName=crimedb
      - HttpClientsDns:PoliceClient=http://rep_crime01.police.api
      - EventBusSettings:HostAddress=rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "8001:80"

  rep_crime01.police.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:PoliceContext=Server=sqldata;Database=PoliceDb;User=sa;Password=Passw0rd2021;
    depends_on:
      - sqldata
    ports:
      - "8002:80"

  rep_crime01.crimefeedback:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - EventBusSettings:HostAddress=rabbitmq
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
